# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

---
#################################
####       INTERFACES        ####
#################################
srl_nokia-interfaces:interface:
  - name: ethernet-1/1
    admin-state: enable
    subinterface:
      - index: 0
        admin-state: enable
        ipv6:
          address:
            - ip-prefix: 2002::192:168:11:1/127
  - name: ethernet-1/2
    admin-state: enable
    subinterface:
      - index: 0
        admin-state: enable
        ipv6:
          address:
            - ip-prefix: 2002::192:168:21:1/127
  - name: ethernet-1/3
    admin-state: enable
    subinterface:
      - index: 0
        admin-state: enable
        ipv6:
          address:
            - ip-prefix: 2002::192:168:31:1/127
  - name: lo0
    admin-state: enable
    subinterface:
      - index: 0
        admin-state: enable
        ipv4:
          address:
            - ip-prefix: 10.0.2.1/32
        ipv6:
          address:
            - ip-prefix: 2002::10:0:2:1/128

#################################
####    NETWORK INSTANCE     ####
#################################
srl_nokia-network-instance:network-instance:
  - name: default
    interface:
      - name: ethernet-1/1.0
      - name: ethernet-1/2.0
      - name: ethernet-1/3.0
      - name: lo0.0
    protocols:
      srl_nokia-bgp:bgp:
        admin-state: enable
        autonomous-system: 201
        router-id: 10.0.2.1
        ebgp-default-policy:
          import-reject-all: false
          export-reject-all: false
        group:
          - group-name: eBGPv6
            ipv4-unicast:
              admin-state: enable
              advertise-ipv6-next-hops: true
              receive-ipv6-next-hops: true
            ipv6-unicast:
              admin-state: enable
        ipv4-unicast:
          multipath:
            allow-multiple-as: true
            max-paths-level-1: 64
            max-paths-level-2: 64
        ipv6-unicast:
          multipath:
            allow-multiple-as: true
            max-paths-level-1: 64
            max-paths-level-2: 64
        neighbor:
          - peer-address: 2002::192:168:11:0
            admin-state: enable
            peer-as: 101
            peer-group: eBGPv6
          - peer-address: 2002::192:168:21:0
            admin-state: enable
            peer-as: 102
            peer-group: eBGPv6
          - peer-address: 2002::192:168:31:0
            admin-state: enable
            peer-as: 103
            peer-group: eBGPv6
